name: Reusable CTB Enforcement

on:
  workflow_call:
    inputs:
      enforcement_mode:
        description: 'Enforcement mode (standard or strict)'
        required: false
        type: string
        default: 'standard'
    outputs:
      status:
        description: 'Enforcement status (PASSED or FAILED)'
        value: ${{ jobs.enforce.outputs.status }}

jobs:
  enforce:
    name: CTB Doctrine Enforcement
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.enforcement.outputs.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Make enforcement script executable
        run: |
          if [ -f "global-config/scripts/ctb_enforce.sh" ]; then
            chmod +x global-config/scripts/ctb_enforce.sh
          fi

      - name: Run CTB Enforcement
        id: enforcement
        run: |
          if [ -f "global-config/scripts/ctb_enforce.sh" ]; then
            bash global-config/scripts/ctb_enforce.sh
            echo "status=PASSED" >> $GITHUB_OUTPUT
          else
            echo "::warning::CTB enforcement script not found - skipping"
            echo "status=SKIPPED" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Upload enforcement log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ctb-enforcement-log
          path: logs/ctb_enforcement.log
          retention-days: 30

      - name: Enforcement summary
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "CTB Enforcement Complete"
          echo "Status: ${{ steps.enforcement.outputs.status }}"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
