name: Auto CTB Sync

on:
  schedule:
    # Check for updates daily at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:
    # Allow manual trigger

# Silence email notifications
notifications:
  email: false

jobs:
  auto-sync:
    runs-on: ubuntu-latest
    name: Auto-Sync from IMO-Creator

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "CTB Auto-Sync Bot"
          git config user.email "ctb-sync@barton-enterprises.com"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install ts-node globally
        run: npm install -g ts-node typescript

      - name: Make CTB update script executable
        run: |
          if [ -f "scripts/ctb_auto_update.sh" ]; then
            chmod +x scripts/ctb_auto_update.sh
          else
            echo "::error::CTB auto-update script not found"
            exit 1
          fi

      - name: Check for CTB updates
        id: check_updates
        run: |
          # Get current version
          CURRENT_VERSION=$(cat ctb-template/version.json | grep -o '"ctb_version"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

          # Get latest version from IMO-Creator
          TEMP_DIR=$(mktemp -d)
          git clone --depth 1 https://github.com/djb258/imo-creator.git "$TEMP_DIR" > /dev/null 2>&1
          NEW_VERSION=$(cat "$TEMP_DIR/ctb-template/version.json" | grep -o '"ctb_version"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          rm -rf "$TEMP_DIR"

          if [ "$CURRENT_VERSION" != "$NEW_VERSION" ]; then
            echo "update_available=true" >> $GITHUB_OUTPUT
            echo "✅ Update available: $CURRENT_VERSION → $NEW_VERSION"
          else
            echo "update_available=false" >> $GITHUB_OUTPUT
            echo "✅ Already up to date: $CURRENT_VERSION"
          fi

      - name: Run CTB Auto-Update
        if: steps.check_updates.outputs.update_available == 'true'
        run: |
          echo "🔄 Running CTB auto-update..."
          bash scripts/ctb_auto_update.sh <<< 'y'  # Auto-accept workflow updates

      - name: Commit and push updates
        if: steps.check_updates.outputs.update_available == 'true'
        run: |
          # Check if there are changes
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          # Stage all CTB updates
          git add -A

          # Create commit message
          NEW_VERSION="${{ steps.check_updates.outputs.new_version }}"
          CURRENT_VERSION="${{ steps.check_updates.outputs.current_version }}"

          git commit -m "🔄 Auto-Sync: CTB Update $CURRENT_VERSION → $NEW_VERSION

Automatically synced from IMO-Creator master repository.

Changes applied and executed:
- Updated manual/, drivers/, viewer-api/ structures
- Updated GitHub Actions workflows
- Ran npm install (if package.json changed)
- Executed CTB health checks
- Validated doctrine compliance
- Rebuilt TypeScript
- Ran tests

Version: $NEW_VERSION
Sync: Automated
Source: https://github.com/djb258/imo-creator

🤖 Auto-synced by CTB Auto-Sync Bot"

          # Push changes
          git push origin HEAD

      - name: Create PR instead of direct push (optional)
        if: steps.check_updates.outputs.update_available == 'true' && github.event_name == 'schedule'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🔄 Auto-Sync: CTB Update ${{ steps.check_updates.outputs.current_version }} → ${{ steps.check_updates.outputs.new_version }}"
          branch: auto-ctb-sync-${{ steps.check_updates.outputs.new_version }}
          title: "🔄 CTB Auto-Sync: Update to v${{ steps.check_updates.outputs.new_version }}"
          body: |
            ## Automated CTB Update

            **Current Version**: ${{ steps.check_updates.outputs.current_version }}
            **New Version**: ${{ steps.check_updates.outputs.new_version }}

            ### Changes Applied

            - ✅ Updated `manual/` - System documentation
            - ✅ Updated `drivers/` - Vendor implementations
            - ✅ Updated `viewer-api/` - External API layer
            - ✅ Updated `.github/workflows/` - CI/CD workflows
            - ✅ Updated `docs/ctb/` - CTB documentation

            ### Executed

            - ✅ `npm install` - Dependencies updated
            - ✅ Health checks - System validated
            - ✅ Doctrine compliance - Barton policy enforced
            - ✅ TypeScript build - Compilation verified
            - ✅ Tests - All tests passed

            ### Review

            This PR was automatically created by the CTB Auto-Sync system. Please review the changes and merge when ready.

            **Source**: [IMO-Creator v${{ steps.check_updates.outputs.new_version }}](https://github.com/djb258/imo-creator)

            ---
            🤖 Auto-synced by CTB Auto-Sync Bot

      - name: No updates available
        if: steps.check_updates.outputs.update_available != 'true'
        run: |
          echo "✅ CTB is already up to date"
          echo "Current version: ${{ steps.check_updates.outputs.current_version }}"
