name: CTB Update Task
description: Track CTB template updates and version releases
title: "[CTB]: v"
labels: ["ctb-update", "documentation"]
projects: ["djb258/1"]
body:
  - type: markdown
    attributes:
      value: |
        ## CTB Update Task
        Track updates to the Christmas Tree Backbone (CTB) template

  - type: input
    id: version
    attributes:
      label: CTB Version
      description: Version number for this update
      placeholder: "1.3.2"
    validations:
      required: true

  - type: dropdown
    id: update-type
    attributes:
      label: Update Type
      description: What type of update is this?
      options:
        - Major Release (Breaking changes)
        - Minor Release (New features)
        - Patch Release (Bug fixes)
        - Hotfix (Critical fix)
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Changes Summary
      description: What changes are included in this update?
      placeholder: |
        - New feature: Role-Based System Manual
        - Enhancement: Auto-execution system
        - Fix: Workflow syntax errors
    validations:
      required: true

  - type: checkboxes
    id: components
    attributes:
      label: Updated Components
      description: Which CTB components are being updated?
      options:
        - label: ctb-template/ (Template structure)
        - label: manual/ (System documentation)
        - label: drivers/ (Vendor implementations)
        - label: viewer-api/ (External API layer)
        - label: .github/workflows/ (CI/CD workflows)
        - label: docs/ctb/ (CTB documentation)
        - label: global-config/ (Global configuration)
        - label: scripts/ (Automation scripts)

  - type: checkboxes
    id: propagation
    attributes:
      label: Propagation Checklist
      description: Steps to propagate this update
      options:
        - label: Update version.json with new version
        - label: Update CTB_VERSION_HISTORY.md
        - label: Test auto-update script locally
        - label: Verify workflow templates in ctb-template/
        - label: Push to IMO-Creator master branch
        - label: Trigger auto-sync in child repos
        - label: Verify propagation to at least one child repo

  - type: textarea
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: List any breaking changes (if applicable)
      placeholder: Describe breaking changes and migration steps
    validations:
      required: false

  - type: textarea
    id: testing
    attributes:
      label: Testing Notes
      description: How should this update be tested?
      placeholder: |
        1. Run ctb_auto_update.sh
        2. Verify npm install completes
        3. Check health status
        4. Run tests
    validations:
      required: false
