name: BMAD Solo
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.github/ISSUE_TEMPLATE/**'
  push:
    branches: [ main, master ]
jobs:
  basic_tests:
    runs-on: ubuntu-latest
    if: ${{ vars.BMAD_STRICT == '1' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npm test || echo "[BMAD Solo] No tests configured"
      - run: npm run build || echo "[BMAD Solo] No build script"
  benchmark:
    runs-on: ubuntu-latest
    if: ${{ vars.BMAD_BENCHMARK == '1' }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x bmad/*.sh || true
          echo "[BMAD Solo] Optional benchmarking enabled"
          ./bmad/measure.sh echo "CI benchmark complete" || true