name: Update Whimsical Diagram

on:
  push:
    branches:
      - '**'

jobs:
  update-whimsical:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml
        
    - name: Generate Whimsical diagram data
      run: |
        python tools/whimsical_visualizer.py . --export whimsical.json
        
    - name: Push to Whimsical
      env:
        WHIMSICAL_API_KEY: ${{ secrets.WHIMSICAL_API_KEY }}
      run: |
        python tools/push_whimsical.py whimsical.json
        
    - name: Upload diagram artifacts
      uses: actions/upload-artifact@v3
      with:
        name: whimsical-diagrams
        path: |
          whimsical.json
          .whimsical/
        retention-days: 7